name: flutter_base
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 权限
  permission_handler: ^4.1.0
  #  oktoast: any
  #  decorated_flutter: ^0.12.2
  # 网络请求库
  dio: ^3.0.8
  # 页面路由
  #  fluro: ^1.7.8
  cached_network_image: ^2.1.0+1
  # 屏幕适配
  flutter_screenutil: ^4.0.3+3
  # 下拉上拉
  flutter_easyrefresh: ^2.0.8
  # toast
  fluttertoast: ^7.1.8
  # SP
  shared_preferences: ^0.5.5
  # 状态管理
  provider: ^6.0.1
  # 图片选择
  #  image_picker: any
  #  flukit: ^1.0.2
  # 地图
  #  amap_map_fluttify: ^0.20.0
  #   图片选择
  image_picker: ^0.6.7+14
  # url_launcher
  url_launcher: ^5.2.3
  #获取app信息
  package_info: ^0.4.0+12
  device_info: ^0.4.1+3
  #获取版本信息
  #  event_bus: ^1.1.0 #事件监听
  #Apk安装插件
  #  install_plugin: any
  #登陆插件
  font_awesome_flutter: ^8.5.0
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  # 播放声音
  #  audioplayers: ^0.13.5
  # 日期选择 修复本身版本适配问题
  #  flutter_pickers: ^1.0.2
  #  photo_view: ^0.10.3
  # path_provider
  path_provider: ^1.6.11
  # pdf_view
  flutter_cached_pdfview: ^0.2.8
  flutter_vertical_marquee: ^0.2.3
  # 多选
  multiselect_formfield: ^0.1.5
  flutter_easyloading: ^2.2.2
  decimal: ^0.3.0
  numberpicker: ^1.3.0
  # 选择文件 之后可删除选择图片，以此代替
  file_picker: ^1.3.8

  flutter_swiper: ^1.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # doc pdf 预览
  flutter_filereader: ^2.0.0

  # UI库
  bruno: ^2.0.0

  intl: ^0.17.0
  # html
  flutter_html: ^0.11.1

  # 统计
  umeng_common_sdk: ^1.2.3

  # webview
  webview_flutter:  ^0.3.20

  #加密解密
  encrypt: ^5.0.1

  #扫码
  qr_code_scanner: ^0.3.5

  #git://39.106.125.67:10105/flutter/flutter_log.git
#  flutter_log:
    #本地依赖
    #path: ../yc_project/flutter_log
    #线上依赖
#    git:
#      url: git://39.106.125.67:10105/flutter/flutter_log.git

  flutter_printer:
#    本地依赖
    path: ../../yc_project/flutter_printer
    #线上依赖
#    git:
#      url: git://39.106.125.67:10105/flutter/flutter_printer.git

  flutter_calendar:
    #本地依赖
    path: ../../yc_project/flutter_calendar
    #线上依赖
#    git:
#      url: git://39.106.125.67:10105/flutter/flutter_calendar.git
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/3.0x/
    - assets/images/weather/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
